AWSTemplateFormatVersion: 2010-09-09
Description: >
    Cloud Watch Rule for sending Emails after CodeBuild 
# created by wolfgang unger - 6.2018

Resources:
  MyRule:
    Type: "AWS::Events::Rule"
    Properties: 
        Description: Rule by W.Unger
        Name: CodeBuildRule
        #ScheduleExpression: String
        State: "ENABLED"
        Targets:
          - 
            Arn: "arn:aws:sns:eu-central-1:016973021151:CodeBuildDemoTopic" 
            Id: "CodeBuildTopic"
        EventPattern: 
          source: 
            - "aws.codebuild"
          detail-type: 
            - "CodeBuild Build State Change"
          detail: 
           build-status: 
            - "SUCCEEDED"
            - "FAILED"
           projectname:
            - "lambda1"
            - "codebuild1"



