######################################################################################
#  Description
######################################################################################

Description: >
    docker ecs test (tomcat image) - tomcat image with port 8080 + env variables
#  by wolfgang unger 9.3.2018
######################################################################################
#  Parameters
######################################################################################

Parameters: 

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: env-variables

     # variables from the systems manager parameter store    
    EnvironmentVariable1:
        Description: Please enter Environment Variable 1
        Type: 'AWS::SSM::Parameter::Value<String>'
        Default: ungerw-parameter1
        
    #EnvironmentVariable2:
    #    Type: 'AWS::SSM::Parameter::Value<String>'



######################################################################################
#  Resources
######################################################################################

Resources:

  MasterStorage:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
      - Key: Name
        Value: !Ref EnvironmentVariable1
      PerformanceMode: generalPurpose


#####################################################################################
#  Outputs
######################################################################################

Outputs:

    MasterStorage:
        Description: A reference to the MasterStorage
        Value: !Ref MasterStorage
        Export:
            #!GetAtt MasterELB.LoadBalancerFullName
            #Name: !GetAtt MasterStorage.KmsKeyId 
            #Name: !Ref  MasterStorage
            Name: !Sub '${AWS::StackName}-FileSystem'


    