
Description: >
    SAM Function
# Wolfgang Unger 1.6.2018 
Resources:
  MySQSLambda:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
           S3Bucket: 's3://eu-central-1.amazonaws.com/cf-templates-btx0hqlvwdq-eu-central-1/'
           S3Key: 'MyFunction.zip'
        #DeadLetterConfig:
        #    DeadLetterConfig
        Description: 'Lambda SQS Function'
        #Environment:
        #    Environment
        FunctionName: LambdaSQS
        Handler: com.unw.demo.LambdaFunctionHandler
        #KmsKeyArn: String
        MemorySize: 256
        ReservedConcurrentExecutions: 1
        Role: LambdaServiceRole
        Runtime: java8
        Timeout: 60
        #TracingConfig:
        #    TracingConfig
        #VpcConfig:
        #    VPCConfig
        #Tags: 
        #    Resource Tag




