Parameters:
  Param1 :
    Type : 'AWS::SSM::Parameter::Value<String>'
    #Default: ungerw-parameter1
    Default: VGARAGE_URL
  #Param2 :
  #  Type : 'AWS::SSM::Parameter::Value<AWS::EC2::KeyPair::KeyName>'
  #  Default: ungerw-parameter2
    #Default: test value 2
    

Resources:

 MasterStorage1:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
      - Key: Name
        Value: !Sub ${Param1}
        #Value: !Sub 'AWS::SSM::Parameter::Value<ungerw-parameter1>'
        #Value: !Sub arn:aws:iam::431271371214:user/Wolfgang.Unger@nttdata.com:parameter/ungerw-parameter1
        # arn:aws:ssm:eu-central-1:#{AWS::AccountId}:parameter/ungerw-parameter1
      PerformanceMode: generalPurpose
      
# MasterStorage2:
#    Type: 'AWS::EFS::FileSystem'
#    Properties:
#      FileSystemTags:
#      - Key: Name
#        Value: !Sub ${Param2}
#      PerformanceMode: generalPurpose